version: "3.9"

services:
  tylt-client-dev:
    build:
      context: .
      target: dev
    container_name: tylt-client-dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PROD=false
      - API_BASE_URL=http://localhost:5000
      - PUBLIC_BASE_URL=http://localhost:3000
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    profiles: ["dev"]

  tylt-client-prod:
    build:
      context: .
      target: prod
    container_name: tylt-client-prod
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PROD=true
      - PROD_API_BASE_URL=https://tylt-feedback-form-server-production.up.railway.app
      - PROD_PUBLIC_BASE_URL=https://tylt-feedback-form-client.vercel.app
    command: npm start
    profiles: ["prod"]
